-- Actualiza metadatos de películas ya cargadas (sin borrar el resto de datos).
-- Uso: mysql -u jota -p db_cine < scripts/update-pelicula-metadatos.sql

UPDATE pelicula SET descripcion = 'La princesa Leia cae prisionera del Imperio al intentar proteger los planos de la Estrella de la Muerte. Luke Skywalker y Han Solo se unen a la rebelión para rescatarla y destruir la superarma.', puntaje = 8.6, anio = 1977, duracion_minutos = 121, director = 'George Lucas', clasificacion = 'ATP' WHERE id = 1;
UPDATE pelicula SET descripcion = 'Tras el ataque a Hoth, Luke entrena con Yoda mientras Han y Leia huyen del Imperio. Darth Vader revela un secreto que cambia el destino de la galaxia.', puntaje = 8.7, anio = 1980, duracion_minutos = 124, director = 'Irvin Kershner', clasificacion = 'ATP' WHERE id = 2;
UPDATE pelicula SET descripcion = 'La Alianza Rebelde prepara un asalto a la segunda Estrella de la Muerte mientras Luke intenta redimir a su padre y enfrentar al Emperador Palpatine.', puntaje = 8.3, anio = 1983, duracion_minutos = 131, director = 'Richard Marquand', clasificacion = 'ATP' WHERE id = 3;
UPDATE pelicula SET descripcion = 'Dos Jedi protegen a la reina Amidala en Naboo y descubren a Anakin Skywalker, un niño con un potencial extraordinario en la Fuerza.', puntaje = 6.5, anio = 1999, duracion_minutos = 136, director = 'George Lucas', clasificacion = 'ATP' WHERE id = 4;
UPDATE pelicula SET descripcion = 'Treinta años después de la Caída del Imperio, la Primera Orden amenaza la galaxia. Rey, Finn y la Resistencia buscan a Luke Skywalker.', puntaje = 7.8, anio = 2015, duracion_minutos = 138, director = 'J. J. Abrams', clasificacion = '+13' WHERE id = 5;
UPDATE pelicula SET descripcion = 'Una soldado desertora y un grupo de rebeldes se infiltran en Scarif para robar los planos de la primera Estrella de la Muerte.', puntaje = 7.6, anio = 2016, duracion_minutos = 133, director = 'Gareth Edwards', clasificacion = '+13' WHERE id = 6;
UPDATE pelicula SET descripcion = 'El millonario Bruce Wayne se convierte en Batman para detener al Joker, quien desata el caos en Ciudad Gótica.', puntaje = 7.5, anio = 1989, duracion_minutos = 126, director = 'Tim Burton', clasificacion = '+13' WHERE id = 7;
UPDATE pelicula SET descripcion = 'Tras años de entrenamiento en la Liga de las Sombras, Bruce Wayne regresa a Gótica para combatir el crimen bajo la identidad de Batman.', puntaje = 8.2, anio = 2005, duracion_minutos = 140, director = 'Christopher Nolan', clasificacion = '+13' WHERE id = 8;
UPDATE pelicula SET descripcion = 'Batman, el teniente Gordon y el fiscal Harvey Dent se enfrentan al Joker, un criminal que busca sumir a Gótica en la anarquía.', puntaje = 9.0, anio = 2008, duracion_minutos = 152, director = 'Christopher Nolan', clasificacion = '+13' WHERE id = 9;
UPDATE pelicula SET descripcion = 'Ocho años después, Batman debe volver cuando Bane escapa de la prisión y planea destruir Ciudad Gótica.', puntaje = 8.4, anio = 2012, duracion_minutos = 164, director = 'Christopher Nolan', clasificacion = '+13' WHERE id = 10;
UPDATE pelicula SET descripcion = 'En su segundo año como vigilante, Batman investiga una serie de asesinatos del Riddler que exponen la corrupción de la élite de Gótica.', puntaje = 7.8, anio = 2022, duracion_minutos = 176, director = 'Matt Reeves', clasificacion = '+13' WHERE id = 11;
UPDATE pelicula SET descripcion = 'Tony Stark, industrial y fabricante de armas, construye una armadura de alta tecnología tras ser secuestrado en Afganistán.', puntaje = 7.9, anio = 2008, duracion_minutos = 126, director = 'Jon Favreau', clasificacion = '+13' WHERE id = 12;
UPDATE pelicula SET descripcion = 'Nick Fury reúne a Iron Man, Capitán América, Thor, Hulk y otros héroes para detener a Loki y su invasión a la Tierra.', puntaje = 8.0, anio = 2012, duracion_minutos = 143, director = 'Joss Whedon', clasificacion = '+13' WHERE id = 13;
UPDATE pelicula SET descripcion = 'Tras ser desenmascarado, Peter Parker pide ayuda al Doctor Strange; un hechizo mal conjurado abre el multiverso y trae villanos de otras realidades.', puntaje = 8.2, anio = 2021, duracion_minutos = 148, director = 'Jon Watts', clasificacion = '+13' WHERE id = 14;
UPDATE pelicula SET descripcion = 'Tras la muerte de su padre, T''Challa regresa a Wakanda para ser rey y enfrentar a Killmonger, quien cuestiona el aislamiento del país.', puntaje = 7.3, anio = 2018, duracion_minutos = 134, director = 'Ryan Coogler', clasificacion = '+13' WHERE id = 15;
UPDATE pelicula SET descripcion = 'Peter Quill roba un orbe codiciado por Ronan el Acusador. Con un grupo de inadaptados, deberá salvar la galaxia.', puntaje = 8.0, anio = 2014, duracion_minutos = 121, director = 'James Gunn', clasificacion = '+13' WHERE id = 16;
UPDATE pelicula SET descripcion = 'Harry Potter descubre que es mago e ingresa a Hogwarts, donde descubre un misterio ligado a la piedra filosofal y al mago que mató a sus padres.', puntaje = 7.6, anio = 2001, duracion_minutos = 152, director = 'Chris Columbus', clasificacion = 'ATP' WHERE id = 17;
UPDATE pelicula SET descripcion = 'El hobbit Frodo Bolsón hereda el Anillo Único y parte con la Comunidad hacia el Monte del Destino para destruirlo antes de que Sauron lo recupere.', puntaje = 8.9, anio = 2001, duracion_minutos = 178, director = 'Peter Jackson', clasificacion = '+13' WHERE id = 18;
UPDATE pelicula SET descripcion = 'Un parque temático con dinosaurios clonados abre en una isla remota, pero un sabotaje desactiva los sistemas de seguridad y el caos se desata.', puntaje = 8.2, anio = 1993, duracion_minutos = 127, director = 'Steven Spielberg', clasificacion = '+13' WHERE id = 19;
UPDATE pelicula SET descripcion = 'En 1936, el arqueólogo Indiana Jones es contratado por el gobierno estadounidense para encontrar el Arca de la Alianza antes que los nazis.', puntaje = 8.4, anio = 1981, duracion_minutos = 115, director = 'Steven Spielberg', clasificacion = '+13' WHERE id = 20;
UPDATE pelicula SET descripcion = 'James Bond obtiene el estatus 00 y debe derrotar al banquero Le Chiffre en un torneo de póquer en Montenegro, financiado por organizaciones terroristas.', puntaje = 8.0, anio = 2006, duracion_minutos = 144, director = 'Martin Campbell', clasificacion = '+13' WHERE id = 21;
UPDATE pelicula SET descripcion = 'Brian O''Conner, policía encubierto, se infiltra en el mundo de las carreras callejeras de Los Ángeles para investigar una serie de robos de camiones.', puntaje = 6.8, anio = 2001, duracion_minutos = 106, director = 'Rob Cohen', clasificacion = '+16' WHERE id = 22;
UPDATE pelicula SET descripcion = 'Ethan Hunt y su equipo deben localizar una entidad de inteligencia artificial que amenaza con desestabilizar el orden mundial.', puntaje = 7.6, anio = 2023, duracion_minutos = 163, director = 'Christopher McQuarrie', clasificacion = '+13' WHERE id = 23;
UPDATE pelicula SET descripcion = 'Woody, el juguete favorito de Andy, ve su lugar amenazado cuando llega Buzz Lightyear, quien cree ser un auténtico ranger espacial.', puntaje = 8.3, anio = 1995, duracion_minutos = 81, director = 'John Lasseter', clasificacion = 'ATP' WHERE id = 24;
UPDATE pelicula SET descripcion = 'Un ogro solitario emprende un viaje para rescatar a la princesa Fiona y recuperar su pantano, acompañado por un burro parlanchín.', puntaje = 7.9, anio = 2001, duracion_minutos = 90, director = 'Andrew Adamson, Vicky Jenson', clasificacion = 'ATP' WHERE id = 25;
UPDATE pelicula SET descripcion = 'En la década de 1940, la familia Corleone lucha por mantener su poder en el crimen organizado tras el intento de asesinato del patriarca Vito Corleone.', puntaje = 9.2, anio = 1972, duracion_minutos = 175, director = 'Francis Ford Coppola', clasificacion = '+16' WHERE id = 26;
UPDATE pelicula SET descripcion = 'Forrest Gump, un hombre de Alabama con coeficiente intelectual bajo, relata décadas de su vida entrelazadas con grandes acontecimientos de Estados Unidos.', puntaje = 8.8, anio = 1994, duracion_minutos = 142, director = 'Robert Zemeckis', clasificacion = '+13' WHERE id = 27;
UPDATE pelicula SET descripcion = 'A bordo del RMS Titanic, la aristócrata Rose DeWitt Bukater y el artista Jack Dawson se enamoran mientras el transatlántico se dirige a su trágico final.', puntaje = 7.9, anio = 1997, duracion_minutos = 194, director = 'James Cameron', clasificacion = '+13' WHERE id = 28;
UPDATE pelicula SET descripcion = 'La agente del FBI Clarice Starling solicita la ayuda del caníbal Hannibal Lecter para capturar a Buffalo Bill, un asesino en serie que desolla a sus víctimas.', puntaje = 8.6, anio = 1991, duracion_minutos = 118, director = 'Jonathan Demme', clasificacion = '+16' WHERE id = 29;
UPDATE pelicula SET descripcion = 'Dom Cobb es un ladrón experto en extracción de secretos del subconsciente que acepta la tarea inversa: implantar una idea en la mente de un heredero industrial.', puntaje = 8.8, anio = 2010, duracion_minutos = 148, director = 'Christopher Nolan', clasificacion = '+13' WHERE id = 30;
